services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: mongo-python-app
    depends_on:
      - mongodb
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    stdin_open: true
    entrypoint: [ "ipython" ]

volumes:
  mongo-data:
