services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  jupyterlab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./app/notebooks:/home/jovyan/work
    depends_on:
      - mongodb

volumes:
  mongo-data:
